import type { Messages } from "./ru";

/** English interface texts (D-49). */
export const en: Messages = {
  common: {
    back: "Back",
    loading: "Loading",
    actions: {
      next: "Next",
      confirm: "Confirm",
      pay: "Pay",
      retry: "Retry",
      cancel: "Cancel",
      close: "Done",
    },
  },
  status: {
    bankUnavailable: "Bank is currently unavailable",
    coreNotConnected: "The banking core is not connected.",
    somethingWrong: "Something went wrong",
    tryAgain: "Please try again.",
    sessionExpired: "Session expired",
    signInAgainAndRetry: "Sign in again and retry.",
    signInAgain: "Sign in again.",
  },
  navigation: {
    label: "Main navigation",
    home: "Home",
    pay: "Payments",
    scanQr: "QR",
    settings: "Settings",
    sbp: "SBP",
  },
  mpin: {
    enter: "Enter MPIN",
    create: "Create an MPIN",
    confirm: "Repeat the MPIN",
    mismatch: "The MPINs do not match. Create an MPIN again.",
  },
  otp: {
    sentTo: (destination: string) => `Code sent to ${destination}`,
    resendIn: (seconds: number) => `Resend in ${seconds} s`,
    resend: "Resend code",
    send: "Send code",
    invalid: "Wrong code",
  },
  authMethod: {
    biometric: "Sign in with biometrics",
    mpin: "Sign in with MPIN",
  },
  account: {
    blocked: "Blocked",
  },
  login: {
    title: "Sign in",
    openAccount: "Open an account",
    register: "Register",
    mpinInvalid: "Wrong MPIN. Please try again.",
    unavailable: "The banking core is not connected, so you cannot sign in.",
    notRegistered: "This device is not registered",
    registerFirst: "Register in the mobile bank first.",
    failed: "Could not sign in",
    biometricNotVerified: "Biometrics not confirmed",
    useMpin: "Sign in with your MPIN.",
  },
  openAccount: {
    title: "Open an account",
    savings: "Savings account",
    current: "Current account",
    loans: "Loans",
  },
  registration: {
    stepUnavailable: "This registration step is not available now",
    startAgain: "Start the registration again from the sign-in screen.",
  },
  registerPhone: {
    title: "Registration",
    phone: "Phone number",
    incomplete: "Enter the full number: +7 and 10 digits",
    invalid: "Check the phone number",
  },
  selectSim: {
    title: "Choose a SIM card",
    otpFailed: "The code did not match",
    chooseAgain: "Choose the SIM card again, then enter a new code.",
    notFound: "No SIM card found",
    noneOnDevice: "There is no SIM card available on this device right now.",
    searchAgain: "Search again",
    listLabel: "SIM card",
    slot: (slot: number) => `SIM ${slot}`,
  },
  bindSim: {
    title: "SIM card binding",
    pending: "Binding the SIM card",
    bound: "SIM card bound",
    failed: "Could not bind the SIM card",
    failedHint: "Try again or choose another SIM card.",
    chooseAnother: "Choose another SIM",
  },
  details: {
    title: "Personal details",
    fields: {
      firstName: "First name",
      lastName: "Last name",
      birthDate: "Date of birth (DD.MM.YYYY)",
      "address.postalCode": "Postal code",
      "address.region": "Region",
      "address.city": "City",
      "address.district": "District",
      "address.street": "Street",
      "address.house": "House",
      "address.apartment": "Apartment",
      email: "Email",
      "card.number": "Card number",
      "card.expiry": "Expiry date (MM/YY)",
    },
    getEmailCode: "Get a code by email",
    emailConfirmed: "Email confirmed",
    consentPush: "I agree to receive push notifications",
    consentMarketing: "I agree to receive marketing emails",
    errors: {
      required: "Fill in this field",
      dateFormat: "Date in DD.MM.YYYY format",
      digitsOnly: "Digits only",
      expiryFormat: "MM/YY format",
      checkEmail: "Check the email address",
      confirmEmail: "Confirm the email with the code from the letter",
      age: "Registration is available from age 18",
      checkValue: "Check the value",
    },
  },
  setMpin: {
    title: "MPIN and biometrics",
    biometricToggle: "Use biometric sign-in",
    biometricUnavailable: "Not available on this device",
  },
  onboardingOtp: {
    title: "SMS code",
  },
  home: {
    title: "Home",
    accounts: "Accounts",
    noAccounts: "No accounts yet",
    accountsNotLoaded: "Could not load the accounts.",
    loadFailed: "Could not load the accounts",
  },
  settings: {
    title: "Settings",
    changeMpin: "Change MPIN",
    biometric: "Biometric sign-in",
    language: "Language",
    logout: "Sign out",
    confirmCodeFirst: "Confirm the code first",
    requestCodeAgain: "Request a code and enter it again.",
  },
  changeMpin: {
    title: "Change MPIN",
    changed: "MPIN changed",
    useNewMpin: "Use your new MPIN to sign in.",
  },
  biometricSettings: {
    title: "Biometric sign-in",
    toggle: "Use biometric sign-in",
    unavailable: "Biometrics unavailable",
    unsupported: "This device does not support biometric sign-in.",
  },
  language: {
    title: "Language",
    listLabel: "Interface language",
  },
};
