/**
 * Russian interface texts: the default language (D-49) and the shape of every dictionary.
 * Only application texts live here; banking and user data (account names, numbers) are never translated.
 */
export const ru = {
  common: {
    back: "Назад",
    loading: "Загрузка",
    actions: {
      next: "Далее",
      confirm: "Подтвердить",
      pay: "Оплатить",
      retry: "Повторить",
      cancel: "Отмена",
      close: "Готово",
    },
  },
  status: {
    bankUnavailable: "Банк сейчас недоступен",
    coreNotConnected: "Банковское ядро не подключено.",
    somethingWrong: "Что-то пошло не так",
    tryAgain: "Попробуйте ещё раз.",
    sessionExpired: "Сессия истекла",
    signInAgainAndRetry: "Войдите снова и повторите.",
    signInAgain: "Войдите снова.",
  },
  navigation: {
    label: "Основная навигация",
    home: "Главная",
    pay: "Платежи",
    scanQr: "QR",
    settings: "Настройки",
    sbp: "Функции СБП",
  },
  mpin: {
    enter: "Введите MPIN",
    create: "Придумайте MPIN",
    confirm: "Повторите MPIN",
    mismatch: "MPIN не совпадают. Придумайте MPIN заново.",
  },
  otp: {
    sentTo: (destination: string) => `Код отправлен: ${destination}`,
    resendIn: (seconds: number) => `Отправить ещё раз через ${seconds} с`,
    resend: "Отправить код ещё раз",
    send: "Отправить код",
    invalid: "Неверный код",
  },
  authMethod: {
    biometric: "Войти по биометрии",
    mpin: "Войти по MPIN",
  },
  account: {
    blocked: "Заблокирован",
  },
  transactions: {
    list: "Операции",
    empty: "Операций пока нет",
    pending: "В обработке",
    failure: "Отклонена",
  },
  statement: {
    title: "Мини-выписка",
    notLoaded: "Не удалось загрузить операции.",
    loadFailed: "Не удалось загрузить операции",
    unknownAccount: "Не удалось открыть операции этого счёта",
    backHome: "Вернитесь на главную.",
  },
  login: {
    title: "Вход",
    openAccount: "Открыть счёт",
    register: "Зарегистрироваться",
    mpinInvalid: "Неверный MPIN. Попробуйте ещё раз.",
    unavailable: "Банковское ядро не подключено, войти не получится.",
    notRegistered: "На этом устройстве нет регистрации",
    registerFirst: "Сначала зарегистрируйтесь в мобильном банке.",
    failed: "Не удалось войти",
    biometricNotVerified: "Биометрия не подтверждена",
    useMpin: "Войдите по MPIN.",
  },
  openAccount: {
    title: "Открыть счёт",
    savings: "Сберегательный счёт",
    current: "Текущий счёт",
    loans: "Кредиты",
  },
  registration: {
    stepUnavailable: "Шаг регистрации сейчас недоступен",
    startAgain: "Начните регистрацию заново с экрана входа.",
  },
  registerPhone: {
    title: "Регистрация",
    phone: "Номер телефона",
    incomplete: "Введите номер полностью: +7 и 10 цифр",
    invalid: "Проверьте номер телефона",
  },
  selectSim: {
    title: "Выбор SIM-карты",
    otpFailed: "Код не подошёл",
    chooseAgain: "Выберите SIM-карту ещё раз, затем введите новый код.",
    notFound: "SIM-карта не найдена",
    noneOnDevice: "Сейчас на устройстве нет доступной SIM-карты.",
    searchAgain: "Повторить поиск",
    listLabel: "SIM-карта",
    slot: (slot: number) => `SIM ${slot}`,
  },
  bindSim: {
    title: "Привязка SIM-карты",
    pending: "Привязываем SIM-карту",
    bound: "SIM-карта привязана",
    failed: "Не удалось привязать SIM-карту",
    failedHint: "Попробуйте ещё раз или выберите другую SIM-карту.",
    chooseAnother: "Выбрать другую SIM",
  },
  details: {
    title: "Личные данные",
    fields: {
      firstName: "Имя",
      lastName: "Фамилия",
      birthDate: "Дата рождения (ДД.ММ.ГГГГ)",
      "address.postalCode": "Индекс",
      "address.region": "Регион",
      "address.city": "Город",
      "address.district": "Район",
      "address.street": "Улица",
      "address.house": "Дом",
      "address.apartment": "Квартира",
      email: "Почта",
      "card.number": "Номер карты",
      "card.expiry": "Срок действия (ММ/ГГ)",
    },
    getEmailCode: "Получить код на почту",
    emailConfirmed: "Почта подтверждена",
    consentPush: "Согласен получать push-уведомления",
    consentMarketing: "Согласен получать рекламные рассылки",
    errors: {
      required: "Заполните поле",
      dateFormat: "Дата в формате ДД.ММ.ГГГГ",
      digitsOnly: "Только цифры",
      expiryFormat: "Формат ММ/ГГ",
      checkEmail: "Проверьте адрес почты",
      confirmEmail: "Подтвердите почту кодом из письма",
      age: "Регистрация доступна с 18 лет",
      checkValue: "Проверьте значение",
    },
  },
  setMpin: {
    title: "MPIN и биометрия",
    biometricToggle: "Входить по биометрии",
    biometricUnavailable: "Недоступно на этом устройстве",
  },
  onboardingOtp: {
    title: "Код из СМС",
  },
  home: {
    title: "Главная",
    accounts: "Счета",
    noAccounts: "Счетов пока нет",
    accountsNotLoaded: "Не удалось загрузить счета.",
    loadFailed: "Не удалось загрузить счета",
  },
  settings: {
    title: "Настройки",
    changeMpin: "Сменить MPIN",
    biometric: "Вход по биометрии",
    language: "Язык",
    logout: "Выйти",
    confirmCodeFirst: "Сначала подтвердите код",
    requestCodeAgain: "Запросите код и введите его снова.",
  },
  changeMpin: {
    title: "Сменить MPIN",
    changed: "MPIN изменён",
    useNewMpin: "Входите с новым MPIN.",
  },
  biometricSettings: {
    title: "Вход по биометрии",
    toggle: "Входить по биометрии",
    unavailable: "Биометрия недоступна",
    unsupported: "Это устройство не поддерживает вход по биометрии.",
  },
  language: {
    title: "Язык",
    listLabel: "Язык интерфейса",
  },
};

/** Every dictionary has exactly this shape: a missing or extra text is a compile error. */
export type Messages = typeof ru;
